### ISSUE TITLE
Drop support for old Django versions?

### ISSUE THREAD

**Issue by jleclanche** [django-polymorphic/django-polymorphic#287]
Anyone opposed to dropping support for Django versions older than 1.10? Django 1.11 is now supported in the latest version, 1.10 and 1.11 are the only versions which are still supported upstream, and it looks like there's actually a lot of hacks for these old versions.

This would also mean dropping Python 2.6 support.

I can work on a PR for it if accepted.

**Comment by meshy** [comment]
I've been working towards this indirectly. I was hoping to get the tests running on postgres and mysql (instead of sqlite) first so that they'd be a little more trustworthy when it came to doing this. (See my progress in #282). That said, I'm probably just procrastinating...

[The docs](https://github.com/django-polymorphic/django-polymorphic/blob/d4fde826008b0dfc62994121bf2f2c8a0de293c2/docs/contributing.rst#supported-django-versions) say:

> The current release should be usable with the supported releases of Django; the current stable release and the previous release. Supporting older Django versions is a nice-to-have feature, but not mandatory.

...which seems pretty sensible, if you ask me.

I'm not a maintainer of this project, but I suspect @vdboor might agree that it's about time to break backwards compatibility...Especially with Django 2.0 just round the corner.

**Comment by jleclanche** [comment]
Yeah I think we should drop the old versions before doing this. If anything the 1.8 migration system changes a lot of things.
