### ISSUE TITLE
Failing test on django master // python 3.6

### ISSUE THREAD

**Issue by jleclanche** [django-polymorphic/django-polymorphic#310]
https://travis-ci.org/django-polymorphic/django-polymorphic/jobs/262018540

I don't know why this happens, but should look at it at some point.

**Comment by hobarrera** [comment]
I'm working on this. Using [`assertQuerysetEqual`](https://docs.djangoproject.com/en/1.10/topics/testing/tools/#django.test.TransactionTestCase.assertQuerysetEqual) (instead of casting querysets to strings) fixes this. It appears to be that tests are not run in the same order, so the hardcoded ids don't match.
